name: CI/CD Pipeline

on:
  push:
    branches:
      - 'feature/*'
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run unit tests
        run: npm test

      - name: Static code analysis
        if: ${{ github.event_name == 'pull_request' }}
        run: npm run lint

      - name: Security scan with Semgrep
        if: ${{ github.event_name == 'pull_request' }}
        run: semgrep --config "p/ci" .

      - name: Build Docker image
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        run: docker build -t ${{ secrets.DOCKER_USERNAME | toLower }}/nodejsapp:${{ github.sha }} .

      - name: Push Docker image
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME | toLower }} --password-stdin
          docker push ${{ secrets.DOCKER_USERNAME | toLower }}/nodejsapp:${{ github.sha }}

      - name: Display Docker image checksum
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        run: docker inspect --format='{{index .RepoDigests 0}}' ${{ secrets.DOCKER_USERNAME | toLower }}/nodejsapp:${{ github.sha }}

      - name: Security scan with Trivy
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        run: trivy image ${{ secrets.DOCKER_USERNAME | toLower }}/nodejsapp:${{ github.sha }}
