name: CI/CD Pipeline

on:
  push:
    branches:
      - 'feature/*'
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run unit tests
        run: npm test
#ANALYSE STATIC DU CODE
      - name: Static code analysis
        if: github.event_name == 'pull_request'
        run: npm run lint
# SCAN DE SECURITE AVEC SEMGREP
      - name: Security scan with Semgrep
        if: github.event_name == 'pull_request'
        run: semgrep --config "p/ci" .
# CONSTRUCTION DE L'IMAGE DOCKER
      - name: Build Docker image
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/nodejsapp:${{ github.sha }} .

      - name: Push Docker image
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push ${{ secrets.DOCKER_USERNAME }}/nodejsapp:${{ github.sha }}

      - name: Display Docker image checksum
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          docker inspect --format='{{index .RepoDigests 0}}' ${{ secrets.DOCKER_USERNAME }}/nodejsapp:${{ github.sha }}

# SCAN DE VULNERABILITE AVEC TRIVY
      - name: Security scan with Trivy
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: trivy image ${{ secrets.DOCKER_USERNAME }}/nodejsapp:${{ github.sha }}
